name: Paper Checker
on:
  schedule:
    - cron: '0 12 * * *' # 每天UTC时间12点运行（北京时间晚8点）
  workflow_dispatch: # 允许手动触发

jobs:
  update-papers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install scholarly==1.5.1
        pip install feedparser==6.0.10

    - name: Fetch papers
      run: |
        python fetch_papers.py

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto update papers"
        git push
